# Generated by Django 5.2.8 on 2025-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AddField(
            model_name='movies',
            name='identification',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
